-- Single UPDATE statement for all recipes
-- Using CASE to update 100 recipes in one query

UPDATE recipes_database
SET steps_en = CASE id
  WHEN 1 THEN '1. Cut tofu into cubes and marinate 20 minutes | 2. Cut vegetables into equal pieces | 3. Alternate on skewers | 4. Grill 10 minutes turning | 5. Cook quinoa | 6. Serve skewers on quinoa, sprinkle with sesame'
  WHEN 2 THEN '1. Put all ingredients in blender | 2. Blend 45 seconds until smooth | 3. Adjust consistency with more milk if needed | 4. Serve immediately'
  WHEN 3 THEN '1. Preheat oven to 200°C | 2. Cut sweet potatoes into cubes and roast 20 minutes | 3. Season salmon with lemon, garlic and olive oil | 4. Grill salmon 12 minutes | 5. Sauté asparagus 5 minutes | 6. Serve together with lemon wedge'
  WHEN 4 THEN '1. Mix oats, protein and chia seeds | 2. Add milk and mix well | 3. Add honey | 4. Let rest in fridge overnight | 5. Top with blueberries when serving'
  WHEN 5 THEN '1. Marinate chicken in yogurt and spices 30 minutes | 2. Sauté onion until golden | 3. Add chicken and sear 5 minutes | 4. Add tomatoes and simmer 20 minutes | 5. Cook rice separately | 6. Serve chicken over rice'
  WHEN 6 THEN '1. Mash bananas in bowl | 2. Beat eggs and add to bananas | 3. Add flour, protein and baking powder | 4. Heat non-stick pan | 5. Pour batter in small portions | 6. Cook 2 minutes each side'
  WHEN 7 THEN '1. Drain and flake tuna | 2. Cut tomatoes and cucumber into dice | 3. Rinse and drain chickpeas | 4. Mix all ingredients | 5. Crumble feta on top | 6. Drizzle with vinaigrette'
  WHEN 8 THEN '1. Blend dates and almonds until sticky | 2. Add oats and protein, blend briefly | 3. Add peanut butter | 4. Press into rectangular mold | 5. Sprinkle with chocolate chips | 6. Refrigerate 2 hours and cut into bars'
  WHEN 9 THEN '1. Cut turkey into strips | 2. Stir-fry turkey 5 minutes on high heat | 3. Add grated ginger and vegetables | 4. Stir-fry 5 more minutes | 5. Pour soy sauce | 6. Serve immediately'
  WHEN 10 THEN '1. Brown ground chicken 5 minutes | 2. Add diced vegetables | 3. Pour broth and bring to boil | 4. Add lentils and turmeric | 5. Simmer 25 minutes until tender | 6. Season and serve hot'
  WHEN 11 THEN '1. Grill chicken and cut into strips | 2. Mix yogurt and lemon for sauce | 3. Spread sauce on tortillas | 4. Add romaine, chicken and parmesan | 5. Roll wraps tightly | 6. Cut in half and serve'
  WHEN 12 THEN '1. Preheat oven to 180°C | 2. Beat eggs and milk together | 3. Finely chop all vegetables | 4. Mix vegetables and cheese with eggs | 5. Pour into muffin molds | 6. Bake 18-20 minutes'
  WHEN 13 THEN '1. Sauté onion and pepper 5 minutes | 2. Add beef and brown | 3. Add tomatoes and spices | 4. Simmer 30 minutes on low heat | 5. Add drained beans | 6. Simmer 10 more minutes'
  WHEN 14 THEN '1. Blend acai, banana, blueberries and milk | 2. Pour into bowl | 3. Top with granola in lines | 4. Add shredded coconut | 5. Decorate with fresh blueberries | 6. Serve immediately'
  WHEN 15 THEN '1. Cook rice according to instructions | 2. Sauté minced garlic 1 minute | 3. Add shrimp and cook 3 minutes | 4. Add zucchini rounds | 5. Stir-fry 4 more minutes | 6. Garnish with parsley and serve over rice'
  WHEN 16 THEN '1. Grate cauliflower and cook 5 minutes | 2. Drain and mix with egg and half the cheese | 3. Form crust and bake 20 minutes at 200°C | 4. Spread tomato sauce on base | 5. Add chicken and remaining cheese | 6. Bake 10 more minutes'
  WHEN 17 THEN '1. Cut beef into thin strips | 2. Blanch broccoli 3 minutes | 3. Sear beef 4 minutes on high heat | 4. Add broccoli and teriyaki sauce | 5. Cook noodles separately | 6. Serve garnished with sesame and green onion'
  WHEN 18 THEN '1. Cook quinoa and let cool | 2. Cut tomatoes and cucumber into small dice | 3. Finely chop mint | 4. Mix quinoa, vegetables and chickpeas | 5. Drizzle with lemon juice | 6. Refrigerate 1 hour before serving'
  WHEN 19 THEN '1. Spiralize zucchini into spaghetti | 2. Sauté onion and beef 8 minutes | 3. Add tomatoes and simmer 15 minutes | 4. Sauté zucchini 3 minutes | 5. Serve sauce over zucchini | 6. Garnish with basil and parmesan'
  WHEN 20 THEN '1. Mix chia, milk, cocoa and syrup | 2. Add vanilla and stir well | 3. Let rest 5 minutes and stir again | 4. Refrigerate minimum 4 hours | 5. Top with raspberries before serving'
  WHEN 21 THEN '1. Brown chicken 5 minutes | 2. Add curry paste and cook 2 minutes | 3. Pour coconut milk | 4. Add sweet potato cubes | 5. Simmer 20 minutes | 6. Add spinach and coriander'
  WHEN 22 THEN '1. Cook and mash sweet potatoes | 2. Partially mash beans | 3. Mix with oats, egg and spices | 4. Form 8 patties | 5. Cook 4 minutes each side | 6. Serve with green salad'
  WHEN 23 THEN '1. Peel kiwis and apple | 2. Cut cucumber into pieces | 3. Put all ingredients in blender | 4. Blend 60 seconds until smooth | 5. Serve chilled'
  WHEN 24 THEN '1. Press tofu and cut into slices | 2. Grill tofu 5 minutes each side | 3. Mix peanut butter, soy and lime | 4. Grate cabbage and carrot | 5. Serve tofu on vegetables | 6. Top with peanut sauce'
  WHEN 25 THEN '1. Blend cauliflower into rice grains | 2. Sauté shallots and mushrooms | 3. Add cauliflower and ladle of broth | 4. Cook adding broth gradually | 5. Add parmesan and thyme | 6. Serve immediately'
  WHEN 26 THEN '1. Mix turkey, crumbled feta and egg | 2. Add breadcrumbs, chopped olives and oregano | 3. Form 16 meatballs | 4. Bake 20 minutes at 180°C | 5. Turn halfway through | 6. Serve with light tzatziki'
  WHEN 27 THEN '1. Cook quinoa and cool | 2. Drain corn and beans | 3. Dice tomatoes and avocado | 4. Mix all ingredients | 5. Drizzle with lime juice | 6. Season with fresh coriander'
  WHEN 28 THEN '1. Marinate chicken in yogurt and spices 2h | 2. Grill chicken 15 minutes | 3. Grate cucumber and drain | 4. Mix cucumber, yogurt and mint for raita | 5. Heat naans | 6. Serve chicken with raita and naan'
  WHEN 29 THEN '1. Soak dates 10 minutes in hot water | 2. Blend dates and almonds | 3. Add protein, cocoa and salt | 4. Add coconut oil | 5. Form 12 balls | 6. Refrigerate 30 minutes before serving'
  WHEN 30 THEN '1. Preheat oven to 180°C | 2. Place fish on parchment paper | 3. Add vegetables, lemon slices and dill | 4. Drizzle with olive oil | 5. Close parcels | 6. Bake 15 minutes'
  WHEN 31 THEN '1. Coarsely mash lentils | 2. Mix with oats, carrot, egg and cumin | 3. Form 4 thick patties | 4. Cook 5 minutes each side | 5. Toast buns | 6. Assemble with salad and tomato'
  WHEN 32 THEN '1. Cook rice and let cool | 2. Cut tuna into cubes | 3. Marinate in soy sauce 10 minutes | 4. Dice mango and avocado | 5. Arrange rice in bowls | 6. Top with tuna, edamame and fruits'
  WHEN 33 THEN '1. Blanch broccoli 5 minutes | 2. Beat cottage cheese, eggs and garlic | 3. Arrange broccoli in dish | 4. Pour mixture over | 5. Sprinkle with emmental | 6. Broil 25 minutes at 180°C'
  WHEN 34 THEN '1. Sauté pepper and chorizo | 2. Add tomatoes and paprika | 3. Simmer 10 minutes | 4. Make 4 wells in sauce | 5. Crack an egg in each well | 6. Cover and cook 5 minutes'
  WHEN 35 THEN '1. Rinse and drain konjac noodles | 2. Stir-fry shrimp 3 minutes | 3. Add scrambled eggs | 4. Add noodles and sauce | 5. Add bean sprouts | 6. Garnish with crushed peanuts'
  WHEN 36 THEN '1. Heat dashi broth | 2. Dilute miso paste | 3. Add tofu cubes | 4. Add edamame and wakame | 5. Simmer 5 minutes | 6. Garnish with sliced green onion'
  WHEN 37 THEN '1. Mix flour, protein and cinnamon | 2. Beat eggs and milk | 3. Add liquids to dry ingredients | 4. Let rest 10 minutes | 5. Cook thin crepes | 6. Serve with applesauce'
  WHEN 38 THEN '1. Cut all vegetables into rounds | 2. Arrange alternating in dish | 3. Drizzle with oil and sprinkle herbs | 4. Bake 30 minutes at 180°C | 5. Make 4 wells in vegetables | 6. Crack eggs and cook 10 minutes'
  WHEN 39 THEN '1. Cut salmon into small dice | 2. Coarsely mash avocado | 3. Mix with lime juice | 4. Add chopped chives | 5. Season with sesame oil | 6. Serve on toasted bread'
  WHEN 40 THEN '1. Slice zucchini into thin strips | 2. Brown ground beef | 3. Add tomato sauce and basil | 4. Alternate layers zucchini, meat, ricotta | 5. Finish with mozzarella | 6. Bake 35 minutes at 180°C'
  WHEN 41 THEN '1. Cook quinoa | 2. Grate red cabbage and carrot | 3. Dice beetroot | 4. Roast chickpeas 15 min | 5. Arrange everything in sections in bowls | 6. Drizzle with diluted tahini sauce'
  WHEN 42 THEN '1. Beat eggs and milk | 2. Sauté all vegetables 5 minutes | 3. Pour eggs over vegetables | 4. Crumble goat cheese | 5. Cook 5 minutes on stove, then 15 min in oven | 6. Serve warm or cold'
  WHEN 43 THEN '1. Infuse lemongrass and galangal | 2. Add chicken strips | 3. Pour coconut milk | 4. Add sliced mushrooms | 5. Simmer 15 minutes gently | 6. Garnish with lime leaves'
  WHEN 44 THEN '1. Season and grill fish 8 minutes | 2. Finely grate cabbage | 3. Mix yogurt and lime juice for sauce | 4. Warm tortillas | 5. Flake fish into tortillas | 6. Top with cabbage, sauce and coriander'
  WHEN 45 THEN '1. Mash bananas | 2. Beat eggs and yogurt | 3. Mix flour, protein and baking powder | 4. Combine all ingredients | 5. Pour into mold | 6. Bake 35 minutes at 180°C'
  WHEN 46 THEN '1. Cut fish into cubes | 2. Marinate in lime juice 15 min | 3. Finely slice onion and chili | 4. Cook and cut sweet potato | 5. Mix all ingredients | 6. Serve immediately well chilled'
  WHEN 47 THEN '1. Sear beef 3 minutes on high heat | 2. Remove and reserve | 3. Stir-fry vegetables 4 minutes | 4. Return beef | 5. Add oyster sauce | 6. Sprinkle with sesame'
  WHEN 48 THEN '1. Cook oats in broth 10 minutes | 2. Sauté mushrooms with thyme | 3. Poach eggs 3 minutes | 4. Serve porridge in bowls | 5. Top with mushrooms and egg | 6. Grate parmesan over'
  WHEN 49 THEN '1. Grill eggplant slices | 2. Brown lamb with cinnamon | 3. Add tomato sauce | 4. Beat yogurt and egg | 5. Alternate layers eggplant and meat | 6. Finish with yogurt sauce, bake 40 min'
  WHEN 50 THEN '1. Cut mango and pineapple into pieces | 2. Put all fruits in blender | 3. Add protein and flax seeds | 4. Pour coconut milk | 5. Blend with ice until smooth'
  WHEN 51 THEN '1. Brown ground chicken | 2. Add carrot julienne | 3. Add sweet chili sauce | 4. Place in lettuce leaves | 5. Top with crushed peanuts | 6. Sprinkle with fresh mint'
  WHEN 52 THEN '1. Peel and slice squash thinly | 2. Rub dish with garlic | 3. Layer slices | 4. Mix cream, nutmeg and thyme | 5. Pour over squash | 6. Sprinkle with gruyere, bake 35 min at 180°C'
  WHEN 53 THEN '1. Lightly flatten cutlets | 2. Sear 2 minutes each side | 3. Deglaze with lemon juice | 4. Add capers and butter | 5. Cook rice separately | 6. Serve cutlets over rice, garnish with parsley'
  WHEN 54 THEN '1. Deseed tomatoes and watermelon | 2. Roughly cut all vegetables | 3. Blend with vinegar until smooth | 4. Season and refrigerate 2 hours | 5. Serve well chilled | 6. Garnish with chopped basil'
  WHEN 55 THEN '1. Cut beef into strips | 2. Marinate with spices 15 minutes | 3. Slice peppers and onions | 4. Sear beef 3 minutes | 5. Add vegetables and cook 5 minutes | 6. Serve in tortillas with yogurt'
  WHEN 56 THEN '1. Sear tuna 2 minutes each side | 2. Cook quail eggs 4 minutes | 3. Blanch green beans | 4. Cut tomatoes in half | 5. Arrange all ingredients | 6. Drizzle with vinaigrette'
  WHEN 57 THEN '1. Sauté curry paste 2 minutes | 2. Add tomatoes and chickpeas | 3. Pour coconut milk | 4. Simmer 15 minutes | 5. Add spinach at end of cooking | 6. Serve with brown rice'
  WHEN 58 THEN '1. Rinse and cook quinoa in 400ml water for 15 minutes | 2. Grill chicken with spices 8 minutes each side | 3. Steam broccoli 5 minutes | 4. Cut avocado into slices | 5. Assemble in bowl and garnish with sesame seeds'
  WHEN 59 THEN '1. Beat eggs with fresh cheese | 2. Melt butter in pan | 3. Pour eggs and stir gently | 4. Add salmon pieces | 5. Toast bread | 6. Serve eggs on toast, garnish with chives'
  WHEN 60 THEN '1. Blend cauliflower into couscous texture | 2. Cut tomatoes into small dice | 3. Finely chop parsley and mint | 4. Mix all ingredients | 5. Drizzle with lemon juice | 6. Garnish with pomegranate seeds'
  WHEN 61 THEN '1. Rehydrate sea spaghetti | 2. Open mussels with white wine | 3. Sauté shrimp and garlic | 4. Add drained spaghetti | 5. Add shelled mussels | 6. Sprinkle with chopped parsley'
  WHEN 62 THEN '1. Mix quinoa and grated vegetables | 2. Beat eggs and incorporate | 3. Add flour and cumin | 4. Form 8 patties | 5. Cook 4 minutes each side | 6. Serve with green salad'
  WHEN 63 THEN '1. Sauté pepper and chorizo | 2. Add tomatoes and paprika | 3. Simmer 10 minutes | 4. Make 4 wells in sauce | 5. Crack an egg in each well | 6. Cover and cook 5 minutes'
  WHEN 64 THEN '1. Mix cottage cheese and chives | 2. Cut cucumber and radishes into sticks | 3. Spread cheese on ham | 4. Add vegetables and roll | 5. Cut into pieces | 6. Serve with whole wheat bread'
  WHEN 65 THEN '1. Cook lentils 20 minutes | 2. Sauté onion and garlic | 3. Add tomatoes and spices | 4. Add lentils, beans and corn | 5. Simmer 15 minutes | 6. Serve with brown rice'
  WHEN 66 THEN '1. Cook bulgur and cool | 2. Cut feta into cubes | 3. Chop sun-dried tomatoes | 4. Mix with olives and arugula | 5. Drizzle with vinaigrette | 6. Serve chilled'
  WHEN 67 THEN '1. Cut vegetables into rounds | 2. Arrange in dish | 3. Mix oats, parmesan and oil | 4. Sprinkle over vegetables | 5. Bake 30 minutes at 180°C | 6. Garnish with fresh basil'
  WHEN 68 THEN '1. Infuse star anise in broth 20 minutes | 2. Cook noodles separately | 3. Place noodles and raw beef in bowls | 4. Pour boiling broth | 5. Add bean sprouts | 6. Garnish with fresh coriander'
  WHEN 69 THEN '1. Press zucchini to remove water | 2. Beat eggs and milk | 3. Mix flour and baking powder | 4. Add liquids and zucchini | 5. Add feta cubes | 6. Bake 25 minutes at 180°C'
  WHEN 70 THEN '1. Soak noodles | 2. Stir-fry chicken and garlic | 3. Add broccoli and scrambled eggs | 4. Add drained noodles | 5. Pour soy sauce | 6. Stir-fry 3 minutes on high heat'
  WHEN 71 THEN '1. Steam endives 15 minutes | 2. Wrap each endive in ham | 3. Arrange in dish | 4. Pour seasoned bechamel | 5. Sprinkle with gruyere | 6. Broil 25 minutes at 180°C'
  WHEN 72 THEN '1. Toast bread | 2. Mash avocado with lemon | 3. Poach eggs 3 minutes | 4. Spread avocado on bread | 5. Place poached eggs | 6. Sprinkle chili and seeds'
  WHEN 73 THEN '1. Brown chicken | 2. Add colombo spices | 3. Pour coconut milk and water | 4. Add cubed vegetables | 5. Simmer 30 minutes | 6. Serve with basmati rice'
  WHEN 74 THEN '1. Cut cauliflower into florets | 2. Prepare batter with flour and water | 3. Add spices | 4. Dip cauliflower in batter | 5. Bake 20 minutes at 200°C | 6. Serve with mint yogurt'
  WHEN 75 THEN '1. Cook soft-boiled eggs 6 minutes | 2. Sauté shrimp | 3. Heat miso broth | 4. Cook noodles 3 minutes | 5. Blanch bok choy | 6. Assemble in bowls with all elements'
  WHEN 76 THEN '1. Assemble bread, ham and cheese | 2. Spread bechamel on top | 3. Sprinkle with gruyere | 4. Bake 10 minutes | 5. Serve with green salad'
  WHEN 77 THEN '1. Blanch meat | 2. Cook in broth with carrots 1h | 3. Add mushrooms | 4. Bind with cream and egg yolk | 5. Add lemon juice | 6. Serve with rice'
  WHEN 78 THEN '1. Roll dough thinly | 2. Spread tomato sauce | 3. Distribute torn mozzarella | 4. Add cut cherry tomatoes | 5. Sprinkle with oregano | 6. Bake 12 minutes at 220°C'
  WHEN 79 THEN '1. Blend red berries with yogurt | 2. Add honey and blend | 3. Pour into bowl | 4. Arrange toppings in lines | 5. Sprinkle chia seeds | 6. Serve immediately'
  WHEN 80 THEN '1. Cut vegetables into large pieces | 2. Sauté with spices | 3. Add water and prunes | 4. Simmer 35 minutes | 5. Prepare semolina separately | 6. Serve tagine over semolina'
  WHEN 81 THEN '1. Brown meat | 2. Flambé with cognac | 3. Add wine and broth | 4. Simmer 1h30 on low heat | 5. Add vegetables 30 min before end | 6. Serve with steamed potatoes'
  WHEN 82 THEN '1. Grill chicken 15 minutes | 2. Tear romaine | 3. Slice chicken | 4. Arrange salad and chicken | 5. Add croutons and parmesan | 6. Drizzle with Caesar dressing'
  WHEN 83 THEN '1. Prepare dough with flour, 1 egg and water | 2. Let rest 1h | 3. Cook thin crepe | 4. Add ham, cheese and egg in center | 5. Fold edges | 6. Cook until egg is cooked'
  WHEN 84 THEN '1. Mix almonds and breadcrumbs | 2. Brush fish with mustard | 3. Press almond crust on top | 4. Bake 15 minutes at 180°C | 5. Steam green beans | 6. Serve with lemon wedges'
  WHEN 85 THEN '1. Sauté onion and garlic | 2. Add all cut vegetables | 3. Pour broth | 4. Simmer 25 minutes | 5. Add pasta 10 min before end | 6. Serve with fresh basil'
  WHEN 86 THEN '1. Mix oats and protein | 2. Beat egg with peanut butter | 3. Add maple syrup | 4. Mix all ingredients | 5. Form 12 cookies on tray | 6. Bake 12 minutes at 180°C'
  WHEN 87 THEN '1. Marinate beef in sauce | 2. Blanch broccoli 3 minutes | 3. Sear beef in wok 3 minutes | 4. Add broccoli and ginger | 5. Cook noodles separately | 6. Serve beef over noodles'
  WHEN 88 THEN '1. Roll dough thinly | 2. Brush with mustard | 3. Arrange tomato slices | 4. Add mozzarella slices | 5. Sprinkle with oregano | 6. Bake 20 minutes at 200°C'
  WHEN 89 THEN '1. Cut vegetables into large pieces | 2. Cook in spiced broth | 3. Simmer 30 minutes | 4. Prepare semolina with broth | 5. Let rise 5 minutes | 6. Serve vegetables over semolina'
  WHEN 90 THEN '1. Soak rice paper in water | 2. Shred chicken | 3. Cut mango and carrot into julienne | 4. Arrange filling on paper | 5. Roll tightly | 6. Serve with fish sauce'
  WHEN 91 THEN '1. Slice potatoes thinly | 2. Rub dish with garlic | 3. Layer potatoes | 4. Mix milk, cream and nutmeg | 5. Pour over potatoes | 6. Bake 45 minutes at 160°C'
  WHEN 92 THEN '1. Cook rice | 2. Sauté tofu until golden | 3. Blanch and season spinach | 4. Sauté carrots and mushrooms separately | 5. Arrange rice and toppings in sections | 6. Serve with gochujang'
  WHEN 93 THEN '1. Sauté onion and curry | 2. Add butternut cubes | 3. Pour broth | 4. Simmer 25 minutes | 5. Blend until smooth | 6. Add coconut milk, garnish with coriander'
  WHEN 94 THEN '1. Chop beef with knife | 2. Finely chop shallot and pickles | 3. Mix with capers | 4. Form 2 steaks, make a well | 5. Place egg yolk | 6. Serve with toasted bread'
  WHEN 95 THEN '1. Coarsely blend chickpeas | 2. Add parsley, onion and spices | 3. Add flour | 4. Form 16 balls | 5. Brush with oil | 6. Bake 25 minutes at 200°C'
  WHEN 96 THEN '1. Brown chicken | 2. Add pepper strips | 3. Add tomatoes and ham | 4. Season with chili | 5. Simmer 30 minutes | 6. Serve with white rice'
  WHEN 97 THEN '1. Press zucchini to remove water | 2. Beat eggs and milk | 3. Mix flour and baking powder | 4. Add zucchini and cheese | 5. Pour into mold | 6. Bake 35 minutes at 180°C'
  WHEN 98 THEN '1. Sauté sliced fennel | 2. Add tomatoes and saffron | 3. Add water and bring to boil | 4. Add cut fish | 5. Simmer 20 minutes | 6. Serve with croutons and rouille'
  WHEN 99 THEN '1. Crush cookies, mix with melted butter | 2. Press into mold | 3. Dissolve gelatin in hot water | 4. Beat cottage cheese, protein and honey | 5. Add gelatin | 6. Pour over base, refrigerate 4h'
  WHEN 100 THEN '1. Sauté squid and shrimp | 2. Add rice and cook until translucent | 3. Pour hot broth with saffron | 4. Arrange mussels on rice | 5. Cook without stirring 20 minutes | 6. Let rest 5 minutes before serving'
  ELSE steps_en
END
WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100);