version: '3.8'

services:
  # Base de données principale
  postgres-perf:
    image: postgres:15
    environment:
      POSTGRES_DB: ryze_performance_test
      POSTGRES_USER: ryze_user
      POSTGRES_PASSWORD: ryze_password
    ports:
      - "5433:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
    networks:
      - ryze-perf-network

  # Cache Redis pour performance
  redis-perf:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    networks:
      - ryze-perf-network

networks:
  ryze-perf-network:
    driver: bridge